# Generated by Django 3.0.7 on 2020-06-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('context', models.TextField(default='', max_length=200)),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('context', models.TextField(max_length=5000)),
                ('subtitle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Subtitle')),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Title')),
            ],
        ),
    ]
