# Generated by Django 3.0.7 on 2020-06-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='Label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
